### ISSUE TITLE
Fatal error: uncss/node_modules/css: missing '{' near line...

### ISSUE THREAD

**Issue by DavidCWebs** [addyosmani/grunt-uncss#149] opened 2015-01-03 17:04 UTC
Thanks for the excellent plugin...Not sure if this is #34 popping up again - it looks very similar.

When the "stylesheets" option is set in my Gruntfile, grunt-uncss fails with this error:

```Fatal error: uncss/node_modules/css: missing '{' near line 173:1```

When I comment this out, grunt-uncss works as expected - though it intermittently throws this error:

Request() error evaluating open() call: Error: socket hang up
Request() error evaluating open() call: Error: connect ECONNREFUSED...

I'm using Ubuntu 14.04 desktop and grunt-uncss version 0.3.8. The uncss is version 0.8.1 and it looks like the function returning the error is in the CSS module, css-parse/index.js.

Grunt-uncss worked perfectly in my previous project, using grunt-uncss v 0.3.6. Though both versions use uncss v 0.8.1, the uncss module nested under grunt-uncss pulls in Phantom JS v1.9.13. 

A shot in the dark (from a non JS person) but could this problem be related to phantom JS? Running top on my system shows phantom taking a high percentage of the CPU while the grunt-uncss task is running.

My workaround sorts this for me, but thought I'd report this FYI

Thanks!

**Comment by XhmikosR** [comment] 2015-01-07 23:53
You should share the project or a minimum test case we can use to reproduce this.

**Comment by t1mmen** [comment] 2015-01-08 11:50
I came across this issue in one of my projects too.

Turned out, the page set in ```options.urls``` didn't correctly link to a CSS file (resulting in a 404), and as a result, uncss returned:

```
Fatal error: uncss/node_modules/css: missing '{' near line 8:1
```

Hope this helps!

**Comment by addyosmani** [comment] 2015-03-02 20:29
@DavidCWebs I know its been a while but I'm curious if the issue you ran into was due to a similar one as the comment above.

**Comment by DavidCWebs** [comment] 2015-03-03 13:58
@addyosmani Actually I had `options.urls` set null, as they're being set dynamically - it's a WordPress site, and I was using Liam Gladdy's method of building a sitemap.json file. Here's a gist of my Gruntfile if it helps:
https://gist.github.com/DavidCWebs/979774ca5b28807744fa 

The Uncss task runs, though it can take a few minutes!

Sorry I didn't reply to the original commenters...

**Comment by XhmikosR** [comment] 2015-03-03 16:10
@DavidCWebs: is the slowdown with all versions or with 0.4.x? Because UnCSS got slower recently, so in that case try grunt-uncss v0.3.8.

**Comment by DavidCWebs** [comment] 2015-03-03 17:14
Thanks @XhmikosR - I'm using 0.3.8 on that site. To be fair the site has a ridiculous amount of styles in ~180 pages, so the delay is understandable...
I just rechecked performance: uncss takes the stylesheet from 256 kB to 107 kB (79 kB after minification) in just under 3 minutes - which is pretty good.

**Comment by XhmikosR** [comment] 2015-03-03 17:17
I guess if you try with 0.4.x the needed time will be 2x :P

**Comment by addyosmani** [comment] 2015-04-04 11:59
> I just rechecked performance: uncss takes the stylesheet from 256 kB to 107 kB (79 kB after minification) in just under 3 minutes - which I reckon is excellent.

Great to hear :)

**Comment by XhmikosR** [comment] 2016-07-09 12:14
Closing this since if it's still an issue, it's an upstream one.

**Closed by XhmikosR** 2016-07-09 12:14 UTC
Labels: question, upstream
