### ISSUE TITLE
Working in Zend framework

### ISSUE THREAD

**Issue by solutac** [addyosmani/grunt-uncss#184] opened 2016-02-26 16:29 UTC
I have this in gruntfile:

```js
uncss: {
    dist: {
        files: [{
            src: 'public/styles/cleancss/tidy.css',
            dest: 'application/views/layouts/default.phtml'
        }]
    }
}
```

Paths are relative to root, but when I type **grunt** to cli, it finish with fatal error:

```
Running "unst:dist" (uncss) task
Fatal error: PhantomJS: Cannot open about:blank
```

What is that mean? **Src** is access from http, but **dest** does not. It is routed by ZF. Is that problem?

**Comment by XhmikosR** [comment] 2016-07-09 12:12
Does this still happen with 0.5.2+?

**Comment by XhmikosR** [comment] 2016-09-20 09:44
Closing due to lack of reply and a repo to reproduce the issue.

**Closed by XhmikosR** 2016-09-20 09:44 UTC
Labels: question
